"""Declarative profiles for all 18 agency agents."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field

from pydantic import BaseModel

from agents import schemas as S


@dataclass(frozen=True)
class AgentProfile:
    key: str  # persona folder + module stem
    name: str
    role: str
    toolbelts: Sequence[str] = field(default_factory=tuple)
    skills: Sequence[str] = field(default_factory=tuple)
    output_schema: type[BaseModel] | None = None
    temperature: float = 0.3
    add_history: bool = False
    num_history_runs: int = 3
    use_json_mode: bool = False


PROFILES: list[AgentProfile] = [
    AgentProfile(
        key="hermes_ops",
        name="Hermes Ops",
        role="Agency Director and primary Orchestrator",
        toolbelts=("parallel_research", "economics", "linear", "spend", "ads_full", "hermes_bridge"),
        skills=(
            "autonomy-levels",
            "roas-guardrails",
            "unit-economics",
            "product-scoring",
            "linear-ops",
            "hermes-ops-playbook",
        ),
        output_schema=S.DirectorDecision,
        temperature=0.25,
        add_history=True,
        num_history_runs=5,
    ),
    AgentProfile(
        key="product_scout",
        name="Product Scout",
        role="Product research and opportunity scoring specialist",
        toolbelts=("parallel_research", "economics", "linear", "hermes_bridge"),
        skills=("product-scoring", "unit-economics", "linear-ops", "product-scout-playbook"),
        output_schema=S.ProductCandidateBatch,
        temperature=0.25,
        use_json_mode=True,
    ),
    AgentProfile(
        key="supplier_sourcer",
        name="Supplier Sourcer",
        role="Supplier discovery, vetting, and landed-cost specialist",
        toolbelts=("parallel_core", "supplier", "linear", "logistics", "hermes_bridge"),
        skills=("supplier-vetting", "unit-economics", "linear-ops"),
        output_schema=S.SupplierShortlist,
        temperature=0.25,
        use_json_mode=True,
    ),
    AgentProfile(
        key="pricing_strategist",
        name="Pricing Strategist",
        role="Pricing, bundling, AOV, and offer architecture specialist",
        toolbelts=("parallel_light", "economics", "linear", "hermes_bridge"),
        skills=("unit-economics", "roas-guardrails"),
        output_schema=S.PriceOfferPlan,
        temperature=0.2,
        use_json_mode=True,
    ),
    AgentProfile(
        key="brand_strategist",
        name="Brand Strategist",
        role="Positioning, brand voice, and differentiation specialist",
        toolbelts=("parallel_light", "linear", "hermes_bridge"),
        skills=("creative-briefing", "compliance-ads-claims"),
        output_schema=S.BrandPositioning,
        temperature=0.45,
        use_json_mode=True,
    ),
    AgentProfile(
        key="creative_director",
        name="Creative Director",
        role="High-converting UGC and creative strategy specialist",
        toolbelts=("parallel_core", "fal", "promptwise", "linear", "hermes_bridge"),
        skills=("ugc-hooks", "creative-briefing", "compliance-ads-claims"),
        output_schema=S.CreativeBriefBatch,
        temperature=0.5,
        use_json_mode=True,
    ),
    AgentProfile(
        key="listing_specialist",
        name="Listing Specialist",
        role="Shopify PDP and conversion specialist",
        toolbelts=("parallel_light", "shopify", "economics", "linear", "hermes_bridge"),
        skills=("listing-cro", "compliance-ads-claims", "unit-economics"),
        output_schema=S.ListingPackage,
        temperature=0.3,
        use_json_mode=True,
    ),
    AgentProfile(
        key="seo_content",
        name="SEO Content",
        role="Organic search and content hub specialist",
        toolbelts=("parallel_core", "linear", "hermes_bridge"),
        skills=("listing-cro",),
        output_schema=S.SEOContentPlan,
        temperature=0.35,
        use_json_mode=True,
    ),
    AgentProfile(
        key="store_builder",
        name="Store Builder",
        role="Shopify store architecture and UX specialist",
        toolbelts=("parallel_light", "shopify", "linear", "hermes_bridge"),
        skills=("listing-cro", "compliance-ads-claims"),
        output_schema=S.StoreIAPlan,
        temperature=0.3,
        use_json_mode=True,
    ),
    AgentProfile(
        key="compliance_officer",
        name="Compliance Officer",
        role="Claims, restricted products, and ads policy specialist",
        toolbelts=("parallel_light", "linear", "hermes_bridge"),
        skills=("compliance-ads-claims", "linear-ops"),
        output_schema=S.ComplianceReview,
        temperature=0.15,
        use_json_mode=True,
    ),
    AgentProfile(
        key="growth_media_buyer",
        name="Growth Media Buyer",
        role="Paid acquisition and ROAS performance specialist",
        toolbelts=("parallel_core", "economics", "linear", "meta_ads", "tiktok_ads", "spend", "hermes_bridge"),
        skills=("roas-guardrails", "paid-social-structure", "unit-economics", "linear-ops"),
        output_schema=S.CampaignPlan,
        temperature=0.25,
        add_history=True,
        use_json_mode=True,
    ),
    AgentProfile(
        key="influencer_manager",
        name="Influencer Manager",
        role="UGC creator sourcing and outreach specialist",
        toolbelts=("parallel_research", "linear", "fal", "hermes_bridge"),
        skills=("ugc-hooks", "creative-briefing", "linear-ops"),
        output_schema=S.InfluencerPlan,
        temperature=0.4,
        use_json_mode=True,
    ),
    AgentProfile(
        key="email_crm",
        name="Email CRM",
        role="Lifecycle email/SMS and retention offers specialist",
        toolbelts=("parallel_light", "economics", "linear", "hermes_bridge"),
        skills=("email-retention", "compliance-ads-claims", "unit-economics"),
        output_schema=S.EmailLifecyclePlan,
        temperature=0.35,
        add_history=True,
        use_json_mode=True,
    ),
    AgentProfile(
        key="customer_success",
        name="Customer Success",
        role="Support macros, returns, and reputation specialist",
        toolbelts=("parallel_light", "linear", "logistics", "hermes_bridge"),
        skills=("customer-support-macros", "fulfillment-playbook", "linear-ops"),
        output_schema=S.SupportMacroPack,
        temperature=0.3,
        add_history=True,
        num_history_runs=6,
        use_json_mode=True,
    ),
    AgentProfile(
        key="fulfillment_ops",
        name="Fulfillment Ops",
        role="Order fulfillment, shipping SLAs, and tracking specialist",
        toolbelts=("parallel_light", "supplier", "logistics", "linear", "hermes_bridge"),
        skills=("fulfillment-playbook", "supplier-vetting"),
        output_schema=S.FulfillmentSLAPlan,
        temperature=0.2,
        use_json_mode=True,
    ),
    AgentProfile(
        key="inventory_planner",
        name="Inventory Planner",
        role="Demand planning, reorder points, and stock-risk specialist",
        toolbelts=("economics", "supplier", "linear", "hermes_bridge"),
        skills=("unit-economics", "supplier-vetting"),
        output_schema=S.InventoryPlan,
        temperature=0.2,
        use_json_mode=True,
    ),
    AgentProfile(
        key="analyst",
        name="Analyst",
        role="Unit economics, performance analysis, and cost control",
        toolbelts=("parallel_core", "economics", "linear", "meta_ads", "tiktok_ads", "hermes_bridge"),
        skills=("unit-economics", "roas-guardrails", "linear-ops"),
        output_schema=S.WeeklyScorecard,
        temperature=0.2,
        add_history=True,
        use_json_mode=True,
    ),
    AgentProfile(
        key="finance_controller",
        name="Finance Controller",
        role="P&L, cashflow, ad budget caps, and vendor payment specialist",
        toolbelts=("economics", "linear", "spend", "hermes_bridge"),
        skills=("unit-economics", "roas-guardrails", "autonomy-levels", "linear-ops"),
        output_schema=S.BudgetDecision,
        temperature=0.15,
        add_history=True,
        use_json_mode=True,
    ),

    # ─── Ops expansion (12) ───────────────────────────────
    AgentProfile(
        key="qa_inspector",
        name="QA Inspector",
        role="Inbound sample and quality inspection specialist",
        toolbelts=('parallel_core', 'linear', 'logistics', 'shopify', 'qa_ops', 'anda_brain', 'analytics', 'hermes_bridge'),
        skills=('qa-inspection-playbook', 'supplier-vetting', 'fulfillment-playbook', 'linear-ops', 'autonomy-levels', 'qa-inspector-playbook'),
        output_schema=S.QAInspectionReport,
        temperature=0.2,
        add_history=False,
        num_history_runs=3,
        use_json_mode=True,
    ),
    AgentProfile(
        key="returns_specialist",
        name="Returns Specialist",
        role="RMA, refunds, exchanges, and reverse logistics specialist",
        toolbelts=('parallel_light', 'linear', 'shopify', 'logistics', 'returns_ops', 'analytics', 'economics', 'hermes_bridge', 'anda_brain'),
        skills=('returns-rma-playbook', 'customer-support-macros', 'unit-economics', 'fulfillment-playbook', 'linear-ops', 'returns-specialist-playbook'),
        output_schema=S.ReturnsOpsPlan,
        temperature=0.25,
        add_history=True,
        num_history_runs=5,
        use_json_mode=True,
    ),
    AgentProfile(
        key="chargeback_specialist",
        name="Chargeback Specialist",
        role="Payment dispute, representment, and chargeback prevention specialist",
        toolbelts=('parallel_core', 'linear', 'shopify', 'chargeback_ops', 'analytics', 'hermes_bridge', 'anda_brain'),
        skills=('chargeback-playbook', 'customer-support-macros', 'roas-guardrails', 'linear-ops', 'chargeback-specialist-playbook'),
        output_schema=S.ChargebackCasePlan,
        temperature=0.2,
        add_history=True,
        num_history_runs=5,
        use_json_mode=True,
    ),
    AgentProfile(
        key="cx_escalations",
        name="CX Escalations",
        role="VIP and escalated customer experience specialist",
        toolbelts=('parallel_light', 'linear', 'shopify', 'cx_ops', 'returns_ops', 'hermes_bridge', 'anda_brain'),
        skills=('cx-escalation-playbook', 'customer-support-macros', 'linear-ops', 'autonomy-levels', 'cx-escalations-playbook'),
        output_schema=S.EscalationPlaybook,
        temperature=0.3,
        add_history=True,
        num_history_runs=5,
        use_json_mode=True,
    ),
    AgentProfile(
        key="logistics_coordinator",
        name="Logistics Coordinator",
        role="Carrier exceptions, tracking recovery, and shipping SLA specialist",
        toolbelts=('parallel_core', 'linear', 'logistics', 'shopify', 'logistics_ops', 'analytics', 'hermes_bridge', 'anda_brain'),
        skills=('logistics-exception-playbook', 'fulfillment-playbook', 'supplier-vetting', 'linear-ops', 'logistics-coordinator-playbook'),
        output_schema=S.LogisticsExceptionPlan,
        temperature=0.25,
        add_history=False,
        num_history_runs=3,
        use_json_mode=True,
    ),
    AgentProfile(
        key="ads_creative_ops",
        name="Ads Creative Ops",
        role="Ad asset pipeline, variant production, and creative ops specialist",
        toolbelts=('parallel_light', 'linear', 'fal', 'promptwise', 'meta_ads', 'tiktok_ads', 'creative_ops', 'hermes_bridge', 'anda_brain'),
        skills=('creative-ops-playbook', 'ugc-hooks', 'creative-briefing', 'compliance-ads-claims', 'paid-social-structure', 'ads-creative-ops-playbook'),
        output_schema=S.CreativeOpsQueue,
        temperature=0.35,
        add_history=False,
        num_history_runs=3,
        use_json_mode=True,
    ),
    AgentProfile(
        key="catalog_ops",
        name="Catalog Ops",
        role="Catalog hygiene, merchandising, and SKU lifecycle specialist",
        toolbelts=('parallel_light', 'linear', 'shopify', 'catalog_ops', 'analytics', 'economics', 'hermes_bridge', 'anda_brain'),
        skills=('catalog-ops-playbook', 'listing-cro', 'unit-economics', 'linear-ops', 'catalog-ops-agent-playbook'),
        output_schema=S.CatalogOpsPlan,
        temperature=0.25,
        add_history=False,
        num_history_runs=3,
        use_json_mode=True,
    ),
    AgentProfile(
        key="risk_fraud_analyst",
        name="Risk Fraud Analyst",
        role="Order fraud, account risk, and abuse detection specialist",
        toolbelts=('parallel_core', 'linear', 'shopify', 'fraud_ops', 'chargeback_ops', 'analytics', 'hermes_bridge', 'anda_brain'),
        skills=('fraud-risk-playbook', 'chargeback-playbook', 'roas-guardrails', 'linear-ops', 'risk-fraud-analyst-playbook'),
        output_schema=S.FraudRiskAssessment,
        temperature=0.2,
        add_history=False,
        num_history_runs=3,
        use_json_mode=True,
    ),
    AgentProfile(
        key="partnerships_manager",
        name="Partnerships Manager",
        role="Affiliate, wholesale, and strategic partnership specialist",
        toolbelts=('parallel_research', 'linear', 'economics', 'partnership_ops', 'hermes_bridge', 'anda_brain'),
        skills=('partnerships-playbook', 'ugc-hooks', 'unit-economics', 'linear-ops', 'partnerships-manager-playbook'),
        output_schema=S.PartnershipPipeline,
        temperature=0.3,
        add_history=True,
        num_history_runs=5,
        use_json_mode=True,
    ),
    AgentProfile(
        key="tax_compliance",
        name="Tax Compliance",
        role="Sales tax, VAT, and fiscal compliance specialist",
        toolbelts=('parallel_core', 'linear', 'shopify', 'tax_ops', 'hermes_bridge', 'anda_brain'),
        skills=('tax-ops-playbook', 'compliance-ads-claims', 'linear-ops', 'autonomy-levels', 'tax-compliance-playbook'),
        output_schema=S.TaxComplianceBrief,
        temperature=0.2,
        add_history=False,
        num_history_runs=3,
        use_json_mode=True,
    ),
    AgentProfile(
        key="community_manager",
        name="Community Manager",
        role="Social community, UGC inbound, and reputation specialist",
        toolbelts=('parallel_core', 'linear', 'fal', 'community_ops', 'hermes_bridge', 'anda_brain'),
        skills=('community-ops-playbook', 'ugc-hooks', 'ugc-hooks', 'customer-support-macros', 'community-manager-playbook'),
        output_schema=S.CommunityOpsPlan,
        temperature=0.35,
        add_history=True,
        num_history_runs=5,
        use_json_mode=True,
    ),
    AgentProfile(
        key="experimentation_lead",
        name="Experimentation Lead",
        role="CRO, A/B testing, and growth experimentation specialist",
        toolbelts=('parallel_research', 'linear', 'shopify', 'experiment_ops', 'analytics', 'economics', 'hermes_bridge', 'anda_brain'),
        skills=('experimentation-playbook', 'listing-cro', 'roas-guardrails', 'unit-economics', 'product-scoring', 'experimentation-lead-playbook'),
        output_schema=S.ExperimentBacklog,
        temperature=0.3,
        add_history=False,
        num_history_runs=3,
        use_json_mode=True,
    ),
]


def profile_by_key(key: str) -> AgentProfile:
    for p in PROFILES:
        if p.key == key:
            return p
    raise KeyError(key)
